#ifndef BG2_IO_ERRORS_H
#define BG2_IO_ERRORS_H

#define BG2IO_NO_ERROR                      0
#define BG2IO_ERR_INVALID_PTR              -1
#define BG2IO_ERR_UNINITIALIZED_BUFFER     -2
#define BG2IO_ERR_INVALID_REQUIRED_SIZE    -3
#define BG2IO_ERR_ITERATOR_OUT_OF_BOUNDS   -4
#define BG2IO_ERR_INVALID_OUT_PARAM_PTR    -5
#define BG2IO_ERR_INSUFFICIENT_LENGTH      -6

#endif